### ISSUE TITLE
Stream logging question

### ISSUE THREAD

**Issue by fredbainbridge** [Eph-It/Automation#22]
How do you envision job stream being logged?  I see a joblog table with a levelId column.  What does this column refer to?  Is there a table and logic yet to be built out that will tie this all together?  I assume the levelId will refer to Warning, Verbose, Information...etc.  Just double checking. Thanks.

**Comment by Ryan2065** [comment]
Yeah - the streams correspond to the JobLog.  The enum JobLogLevelEnum is what I envisioned for logging.

My thought is if the log is generic, it would work for any scripting engine we used if we wanted to expand it further later (for instance, running C# scripts or Python).  That's why it is called JobLog and not PoshLog or something like that, and why I used the naming "level" instead of "streams".
